name: notebook_snippets
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.7
  - tqdm
  - matplotlib
  - seaborn
  - pandas
  - requests
  - ipywidgets
  - google-api-python-client
  - oauth2client
  - pip:
    - lxml
    - pytrends
    - git+https://github.com/joshcarty/google-searchconsole#egg=google-searchconsole
